### ISSUE TITLE
Clang-tidy does not work with MSVC toolchain

### ISSUE THREAD

**Issue by aminya** [MarkSchofield/Toolchain#12]
I have some issues with Clang-tidy when I use this toolchain. Do you know what is going on? 

https://github.com/cpp-best-practices/project_options/pull/34#issuecomment-1003503538

```cmake
FAILED: CMakeFiles/main.dir/Debug/main.cpp.obj
"C:\Program Files\CMake\bin\cmake.exe" -E __run_co_compile --launcher=C:/tools/msys64/mingw64/bin/ccache.exe --tidy="C:/Program Files/LLVM/bin/clang-tidy.exe;-extra-arg=-Wno-unknown-warning-option;-extra-arg=-std=c++17;--extra-arg-before=--driver-mode=cl" --cppcheck="C:/Program Files/Cppcheck/cppcheck.exe;--suppress=missingInclude;--enable=all;--inline-suppr;--inconclusive;--std=c++17" --source=C:\project_options\test\main.cpp -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\cl.exe  /nologo /TP -DFMT_LOCALE -DFMT_SHARED -DCMAKE_INTDIR=\"Debug\" -external:I "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\ATLMFC\include" -external:I "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include" -external:I "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" -external:I "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" -external:I "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" -external:I "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" -external:I "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -external:I C:\project_options\test\build\vcpkg_installed\x64-windows\include -external:I C:\project_options\test\build\vcpkg_installed\x64-windows\share\eigen3\..\..\include\eigen3 -external:W0 /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -MDd /diagnostics:column /W4 /w14242 /w14254 /w14263 /w14265 /w14287 /we4289 /w14296 /w14311 /w14545 /w14546 /w14547 /w14549 /w14555 /w14619 /w14640 /w14826 /w14905 /w14906 /w14928 /permissive- -std:c++17 /showIncludes /FoCMakeFiles\main.dir\Debug\main.cpp.obj /FdCMakeFiles\main.dir\Debug\ /FS -c C:\project_options\test\main.cpp
warning: unknown argument ignored in clang-cl: '-std=c++17' [clang-diagnostic-unknown-argument]
C:\project_options\test\main.cpp:2:10: error: 'fmt/core.h' file not found [clang-diagnostic-error]
#include <fmt/core.h>
         ^~~~~~~~~~~~
23598 warnings and 1 error generated.
Error while processing C:\project_options\test\main.cpp.
Suppressed 23597 warnings (23597 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
ninja: build stopped: subcommand failed.

```

Clang tidy is set here:
https://github.com/cpp-best-practices/project_options/blob/c88a46f951c75a8d43dc0b2282a81f49ceba20f7/src/StaticAnalyzers.cmake#L21

**Comment by MarkSchofield** [comment]
It looks like clang-tidy is being run with `--driver-mode=cl` so that it's using `clang-cl` as the driver. And that seems like a reasonable thing to do, since the build is using `cl.exe` as the compiler. I imagine that there's logic in whatever consumes `CMAKE_CXX_CLANG_TIDY` that makes this determination - probably using `CMAKE_<LANG>_COMPILER_ID` or `CMAKE_<LANG>_COMPILER_FRONTEND_VARIANT` that CMake sets when it's identifying the compiler.

But `clang-cl` complains that the `-std=c++17` isn't known - and that's because that appears to be the `clang` not `clang-cl` option to the compiler. `clang-cl` would probably expect `/std:c++17`.

From the link you provided to the `StaticAnalyzers.cmake`, it's got this logic in the `enable_clang_tidy` macro:

```cmake
    set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY} -extra-arg=-Wno-unknown-warning-option)
    if(${CMAKE_CXX_STANDARD})
      set(CMAKE_CXX_CLANG_TIDY ${CMAKE_CXX_CLANG_TIDY} -extra-arg=-std=c++${CMAKE_CXX_STANDARD})
    endif()
    if(WARNINGS_AS_ERRORS)
      list(APPEND CMAKE_CXX_CLANG_TIDY -warnings-as-errors=*)
    endif()
```

So it's explicitly adding `clang`-parameters to `CMAKE_CXX_CLANG_TIDY`, and not checking to see if the compiler expects `clang` or `clang-cl` style options. Since the `CMAKE_CXX_CLANG_TIDY`-consuming logic accommodates `clang` or `clang-cl`, then `StaticAnalyzers.cmake` should probably accommodate both, too.

That explains the `warning: unknown argument ignored in clang-cl: '-std=c++17'` warning. It's not clear why the header isn't found - is it protected with a check for C++17? I think getting the C++ standard set correctly might help, so addressing the warning first would probably help. Or at least be insightful.

**Comment by MarkSchofield** [comment]
Ah, it looks like the CMake compiler scripts set `CMAKE_CXX_CLANG_TIDY_DRIVER_MODE` to `cl` when the C++ front-end is MSVC-like. Perhaps `StaticAnalyzers.cmake` should check that to see what format options to specify?

**Comment by aminya** [comment]
> Ah, it looks like the CMake compiler scripts set `CMAKE_CXX_CLANG_TIDY_DRIVER_MODE` to `cl` when the C++ front-end is MSVC-like. Perhaps `StaticAnalyzers.cmake` should check that to see what format options to specify?

Thank you. I think this was fixed in 
https://github.com/cpp-best-practices/project_options/pull/54

**Comment by aminya** [comment]
There is one more warning that I get:
https://github.com/cpp-best-practices/project_options/pull/34#pullrequestreview-871497483

Could you take a look and see if you know the reason for it?
