### ISSUE TITLE
Error selecting MSVC toolchain

### ISSUE THREAD

**Issue by SK83RJOSH** [MarkSchofield/Toolchain#41]
When using Windows.MSVC.Toolchain.cmake I get the following error:

```
1> [CMake] -- Using Windows MSVC toolchain
1> [CMake] CMake Error at out/build/Debug/_deps/_msvc_toolchain-src/Windows.MSVC.toolchain.cmake:165 (message):
1> [CMake]   Unable to obtain the compiler version from: C:/Program Files/Microsoft
1> [CMake]   Visual
1> [CMake]   Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/AMD64/cl.exe
1> [CMake] Call Stack (most recent call first):
1> [CMake]   out/build/Debug/_deps/_project_options-src/src/VCEnvironment.cmake:72 (include)
1> [CMake]   out/build/Debug/_deps/_project_options-src/src/Index.cmake:35 (msvc_toolchain)
1> [CMake]   out/build/Debug/_deps/_project_options-src/CMakeLists.txt:3 (include)
1> [CMake] -- Configuring incomplete, errors occurred!
```

I've tracked it down and noticed that:
`C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/AMD64/cl.exe`
Should be:
`C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe`

It appears the issue is [here](https://github.com/MarkSchofield/Toolchain/blob/main/Windows.MSVC.toolchain.cmake#L154) - I assume this should be `CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE` instead?

**Comment by MarkSchofield** [comment]
Looking at the path chunk `Hostx64/AMD64/cl.exe`, the `Hostx64` is the architecture of the tooling to build with ('host architecture'), and `amd64` is the architecture that you're targeting ('target architecture').
* For the 'host architecture', the `Windows.MSVC.Toolchain.cmake` file allows you to set the host architecture through `CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE`, which defaults to 'x64' by default - since that matches the suffix in `Hostx64`.
* For the 'target architecture', the `Windows.MSVC.Toolchain.cmake` file uses `CMAKE_SYSTEM_PROCESSOR` - which the file defaults to 'x64' - as the `CMAKE_VS_PLATFORM_TOOLSET_ARCHITECTURE`.

There's a couple of problems:
1. `CMAKE_SYSTEM_PROCESSOR` should probably default to `CMAKE_HOST_SYSTEM_PROCESSOR` as per [the `CMAKE_SYSTEM_PROCESSOR` documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html). [The `CMAKE_HOST_SYSTEM_PROCESSOR` documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html) says that this would by the value of the `PROCESSOR_ARCHITECTURE` documentation, which is `AMD64` on x86_64 machines.
2. To initialize `CMAKE_VS_PLATFORM_TOOLSET_ARCHITECTURE`, I would then need to map the `CMAKE_SYSTEM_PROCESSOR` values of `AMD64` and `x64` to `x64`.

This is working in the examples, since they always explicitly set `CMAKE_SYSTEM_PROCESSOR` to x64. It's broken for you since you're doing the right thing and setting `CMAKE_SYSTEM_PROCESSOR` to `AMD64`.
